services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: myuser
      DB_PASSWORD: secretpassword
      DB_NAME: rssdb
    ports:
      - "8080:8080"
    depends_on:
      - db
    
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: rssdb
    ports:
      - "5431:5432"
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
      